version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_USER=postgres
  pgadmin: 
      image: dpage/pgadmin4
      container_name: pgadmin
      ports: 
      - "8888:80"
      environment: 
        PGADMIN_DEFAULT_EMAIL: stutzchristian@gmx.de
        PGADMIN_DEFAULT_PASSWORD: abc123
      volumes: 
        - pgadmin-data:/var/lib/pgadmin
  
volumes:
    local_pgdata:
    pgadmin-data:
networks: 
  apex_community_internal:
    external: true



      
      